### ISSUE TITLE
Add signout button

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/The-Green-Alliance#11]
- [ ] Call `firebase.auth().signOut();` when a logout button is clicked

I'd like this as part of a setting tab on the side as we have in years past. See 2018-Core for reference.

**Comment by roshanr10** [comment]
@ShashJar same here

**Comment by roshanr10** [comment]
Adding onto this, I would prefer if this is ONLY possible when the user has internet in the event that is undesirable

**Comment by roshanr10** [comment]
let’s add a pass phrase instead

**Comment by Muirrum** [comment]
What do you mean by a passphrase? Something they have to enter in order to sign out?

**Comment by roshanr10** [comment]
Yes, TBD.
