### ISSUE TITLE
Add Capability of Switching Between App Pages Throughout Match

### ISSUE THREAD

**Issue by shashjar** [FRCteam4909/The-Green-Alliance#2]
Potentially through jquery for the different HTML data pages

**Comment by roshanr10** [comment]
The code should already be set up to work with this: http://www.jquery-steps.com

take a look at https://github.com/The-Green-Alliance/2018-Core/blob/master/app/www/js/main.js#L130-L199

```
$('#wizard_horizontal').steps({
        headerTag: 'h2',
        bodyTag: 'section',
        transitionEffect: 'slideLeft',
        onFinished: function (event, currentIndex) { . . . }
});
````

that's how we implemented it last year
